/*
 *
 * CaloHitHelper.h header template automatically generated by a class generator
 * Creation date : lun. mai 5 2014
 *
 * This file is part of SDHCALEventDisplay libraries.
 * 
 * SDHCALEventDisplay is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 * based upon these libraries are permitted. Any copy of these libraries
 * must include this copyright notice.
 * 
 * SDHCALEventDisplay is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 * 
 * You should have received a copy of the GNU General Public License
 * along with SDHCALEventDisplay.  If not, see <http://www.gnu.org/licenses/>.
 * 
 * @author remi
 * @copyright CNRS , IPNL
 */


#ifndef CALOHITHELPER_H
#define CALOHITHELPER_H

#include "Typedef.h"

namespace sdhcal
{

class OrderedCaloHitList;
class CaloHit;

/** 
 * @brief CaloHitHelper class
 */ 
class CaloHitHelper 
{
public:

	/**
	 *
	 */
	static void CalculateCaloHitProperties(const OrderedCaloHitList &orderedCaloHitList);

protected:

	/**
	 *
	 */
	static float CalculateCaloHitDensity2D(CaloHit *pCaloHit, const CaloHitList &caloHitList);

	/**
	 *
	 */
	static float CalculateCaloHitDensity3D(CaloHit *pCaloHit, const OrderedCaloHitList &orderedCaloHitList);
}; 

} 

#endif  //  CALOHITHELPER_H
