  /// \file Config.h
/*
 *
 * Config.h header template automatically generated by a class generator
 * Creation date : lun. avr. 28 2014
 *
 * This file is part of SDHCALEventDisplay libraries.
 * 
 * SDHCALEventDisplay is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 * based upon these libraries are permitted. Any copy of these libraries
 * must include this copyright notice.
 * 
 * SDHCALEventDisplay is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 * 
 * You should have received a copy of the GNU General Public License
 * along with SDHCALEventDisplay.  If not, see <http://www.gnu.org/licenses/>.
 * 
 * @author Remi Ete
 * @copyright CNRS , IPNL
 */


#ifndef CONFIG_H
#define CONFIG_H

#include <string>

namespace gear
{
 class GearMgr;
}

namespace sdhcal
{

/** 
 * @brief Config class
 */ 
class Config 
{
public:

	/**
	 *
	 */
	static Config *getInstance();

	/**
	 *
	 */
	static void kill();

	/**
	 *
	 */
	void parseXmlConfig(const std::string &xmlFileName);

	/**
	 *
	 */
	void parseGearFile(const std::string &gearFileName);

	/**
	 *
	 */
	gear::GearMgr *getGearMgr() const;


protected:

	/**
		* @brief Ctor
		*/
	Config();

	/**
		* @brief Dtor
		*/
	virtual ~Config();

	// members
	static Config      *m_pInstance;

	gear::GearMgr       *m_pGearMgr;

}; 


inline gear::GearMgr *Config::getGearMgr() const
{
	return m_pGearMgr;
}

} 

#endif  //  CONFIG_H
