  /// \file DetectorStatisticsWindow.h
/*
 *
 * DetectorStatisticsWindow.h header template automatically generated by a class generator
 * Creation date : ven. mai 2 2014
 *
 * This file is part of SDHCALEventDisplay libraries.
 * 
 * SDHCALEventDisplay is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 * based upon these libraries are permitted. Any copy of these libraries
 * must include this copyright notice.
 * 
 * SDHCALEventDisplay is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 * 
 * You should have received a copy of the GNU General Public License
 * along with SDHCALEventDisplay.  If not, see <http://www.gnu.org/licenses/>.
 * 
 * @author Remi Ete
 * @copyright CNRS , IPNL
 */


#ifndef DETECTORSTATISTICSWINDOW_H
#define DETECTORSTATISTICSWINDOW_H

#include "Rtypes.h"
#include "RQ_OBJECT.h"

class TGWindow;

namespace sdhcal
{

/** 
 * @brief DetectorStatisticsWindow class
 */ 
class DetectorStatisticsWindow
{
	RQ_OBJECT("sdhcal::DetectorStatisticsWindow");

 public:
 /**
  * @brief Ctor
  */
 DetectorStatisticsWindow(TGWindow *pParent);

 /**
  * @brief Dtor 
  */
 virtual ~DetectorStatisticsWindow();

protected:

 ClassDef(DetectorStatisticsWindow, 0);
}; 

} 

#endif  //  DETECTORSTATISTICSWINDOW_H
