/*
 *
 * GeometryManager.h header template automatically generated by a class generator
 * Creation date : sam. mai 3 2014
 *
 * This file is part of SDHCALEventDisplay libraries.
 * 
 * SDHCALEventDisplay is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 * based upon these libraries are permitted. Any copy of these libraries
 * must include this copyright notice.
 * 
 * SDHCALEventDisplay is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 * 
 * You should have received a copy of the GNU General Public License
 * along with SDHCALEventDisplay.  If not, see <http://www.gnu.org/licenses/>.
 * 
 * @author Remi Ete
 * @copyright CNRS , IPNL
 */


#ifndef GEOMETRYMANAGER_H
#define GEOMETRYMANAGER_H

class TGeoManager;
class TGeoMaterial;
class TGeoMedium;
class TGeoVolume;

namespace sdhcal
{

class SDHCAL;

/** 
 * @brief GeometryManager class
 */ 
class GeometryManager 
{
 public:
 /**
  * @brief Ctor
  */
 GeometryManager();

 /**
  * @brief Dtor 
  */
 virtual ~GeometryManager();

 /**
  *
  */
 void buildGeometry();

 /**
  *
  */
 TGeoVolume *getTopVolume() const;

 /**
  *
  */
 TGeoManager *getGeoManager() const;

 /**
  *
  */
 SDHCAL *getSDHCAL() const;

protected:

 bool                   m_alreadyBuilt;
 TGeoManager            *m_pGeoManager;
 TGeoMaterial           *m_pTopMaterial;
 TGeoMedium             *m_pTopMedium;
 TGeoVolume             *m_pTopVolume;
 SDHCAL                 *m_pSDHCAL;

}; 


inline TGeoVolume *GeometryManager::getTopVolume() const
{
	return m_pTopVolume;
}



inline TGeoManager *GeometryManager::getGeoManager() const
{
	return m_pGeoManager;
}


inline SDHCAL *GeometryManager::getSDHCAL() const
{
	return m_pSDHCAL;
}

} 

#endif  //  GEOMETRYMANAGER_H
