  /// \file LinkDef.h
/*
 *
 * LinkDef.h header template automatically generated by a class generator
 * Creation date : lun. avr. 28 2014
 *
 * This file is part of SDHCALEventDisplay libraries.
 * 
 * SDHCALEventDisplay is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 * based upon these libraries are permitted. Any copy of these libraries
 * must include this copyright notice.
 * 
 * SDHCALEventDisplay is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 * 
 * You should have received a copy of the GNU General Public License
 * along with SDHCALEventDisplay.  If not, see <http://www.gnu.org/licenses/>.
 * 
 * @author Remi Ete
 * @copyright CNRS , IPNL
 */


#ifndef LINKDEF_H
#define LINKDEF_H


#ifdef __CINT__

#pragma link off all globals;
#pragma link off all classes;
#pragma link off all functions;

#pragma link C++ namespace sdhcal;
#pragma link C++ nestedclasses;
#pragma link C++ class sdhcal::EventNavigator+;
#pragma link C++ class sdhcal::EventManager+;
#pragma link C++ class sdhcal::LcioCollectionFrame+;
#pragma link C++ class sdhcal::DetectorStatisticsWindow+;
#pragma link C++ class sdhcal::DetectorStatisticsFrame+;
#pragma link C++ class sdhcal::DetectorFrame+;
#pragma link C++ class sdhcal::CaloHitFrame+;

#endif  //  __CINT__


#endif  //  LINKDEF_H
