/*
 *
 * OrderedCaloHitList.h header template automatically generated by a class generator
 * Creation date : sam. mai 3 2014
 *
 * This file is part of SDHCALEventDisplay libraries.
 * 
 * SDHCALEventDisplay is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 * based upon these libraries are permitted. Any copy of these libraries
 * must include this copyright notice.
 * 
 * SDHCALEventDisplay is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 * 
 * You should have received a copy of the GNU General Public License
 * along with SDHCALEventDisplay.  If not, see <http://www.gnu.org/licenses/>.
 * 
 * @author Remi Ete
 * @copyright CNRS , IPNL
 */


#ifndef ORDEREDCALOHITLIST_H
#define ORDEREDCALOHITLIST_H

#include <map>

#include "Typedef.h"

namespace sdhcal
{

/** 
 * @brief OrderedCaloHitList class
 */ 
class OrderedCaloHitList : public std::map<unsigned int, CaloHitList> 
{
 public:
 /**
  * @brief Ctor
  */
 OrderedCaloHitList();

 /**
  * @brief Dtor 
  */
 virtual ~OrderedCaloHitList();

 /**
  *
  */
 void show();

 /**
  *
  */
 void hide();

 /**
  *
  */
 void show(unsigned int layer);

 /**
  *
  */
 void hide(unsigned int layer);

 /**
  *
  */
 void show(unsigned int fromLayer, unsigned int toLayer);

 /**
  *
  */
 void hide(unsigned int fromLayer, unsigned int toLayer);

protected:


}; 

} 

#endif  //  ORDEREDCALOHITLIST_H
