  /// \file CaloHit.cc
/*
 *
 * CaloHit.cc source template automatically generated by a class generator
 * Creation date : lun. avr. 28 2014
 *
 * This file is part of SDHCALEventDisplay libraries.
 * 
 * SDHCALEventDisplay is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 * based upon these libraries are permitted. Any copy of these libraries
 * must include this copyright notice.
 * 
 * SDHCALEventDisplay is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 * 
 * You should have received a copy of the GNU General Public License
 * along with SDHCALEventDisplay.  If not, see <http://www.gnu.org/licenses/>.
 * 
 * @author Remi Ete
 * @copyright CNRS , IPNL
 */


#include "CaloHit.h"

// streamlog
#include "streamlog/streamlog.h"

namespace sdhcal
{

CaloHit::CaloHit(unsigned int id, CartesianVector position, CaloHitCell cell, SemiDigitalThreshold semiDigitalThreshold)
 : m_id(id),
   m_position(position),
   m_cell(cell),
   m_semiDigitalThreshold(semiDigitalThreshold),
   m_pEveBoxSet(NULL),
   m_color(0),
   m_transparency(0)
{

}

CaloHit::CaloHit(CaloHit *pCaloHit)
{
	m_position             = pCaloHit->m_position;
	m_cell                 = pCaloHit->m_cell;
	m_semiDigitalThreshold = pCaloHit->m_semiDigitalThreshold;
}


CaloHit::~CaloHit() 
{

}


void CaloHit::setColor(unsigned int color)
{
	if(NULL == m_pEveBoxSet)
		return;

	m_color = color;
	m_pEveBoxSet->SetCurrentDigit(m_id);
	m_pEveBoxSet->DigitColor(color);
}



void CaloHit::setTransparency(unsigned int transparency)
{
	if(NULL == m_pEveBoxSet)
		return;

	m_transparency = transparency;
	m_pEveBoxSet->SetCurrentDigit(m_id);
	m_pEveBoxSet->DigitColor(m_color, transparency);
}



void CaloHit::show()
{
	if(NULL == m_pEveBoxSet)
		return;

	m_pEveBoxSet->SetCurrentDigit(m_id);
	m_pEveBoxSet->DigitColor(m_color, 0);
}



void CaloHit::hide()
{
	if(NULL == m_pEveBoxSet)
		return;


	m_pEveBoxSet->SetCurrentDigit(m_id);
	m_pEveBoxSet->DigitColor(m_color, 100);
}

} 

