/*
 *
 * LcioCollectionFrame.cc source template automatically generated by a class generator
 * Creation date : lun. avr. 28 2014
 *
 * This file is part of SDHCALEventDisplay libraries.
 * 
 * SDHCALEventDisplay is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 * based upon these libraries are permitted. Any copy of these libraries
 * must include this copyright notice.
 * 
 * SDHCALEventDisplay is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 * 
 * You should have received a copy of the GNU General Public License
 * along with SDHCALEventDisplay.  If not, see <http://www.gnu.org/licenses/>.
 * 
 * @author Remi Ete
 * @copyright CNRS , IPNL
 */


#include "LcioCollectionFrame.h"

// root
#include "TGFrame.h"
#include "TGLabel.h"
#include "TGTextEntry.h"

ClassImpQ(sdhcal::LcioCollectionFrame);

namespace sdhcal
{

LcioCollectionFrame::LcioCollectionFrame(TGMainFrame *pMainFrame)
{
	m_pLcioCollectionFrame = new TGGroupFrame(pMainFrame, "Lcio Collections", kHorizontalFrame);

	// sdhcal collection entry
	m_pSDHCALCollectionFrame = new TGHorizontalFrame(m_pLcioCollectionFrame);
	m_pLcioCollectionFrame->AddFrame(m_pSDHCALCollectionFrame);

	m_pSDHCALCollectionLabel = new TGLabel(m_pSDHCALCollectionFrame, "SDHCAL collection");
	m_pSDHCALCollectionLabel->SetWidth(30);
	m_pSDHCALCollectionFrame->AddFrame(m_pSDHCALCollectionLabel, new TGLayoutHints(kLHintsCenterX, 0, 0, 8));

	m_pSDHCALCollectionEntry = new TGTextEntry(m_pSDHCALCollectionFrame);
	m_pSDHCALCollectionEntry->SetText("HCALBarrel");
	m_pSDHCALCollectionFrame->AddFrame(m_pSDHCALCollectionEntry, new TGLayoutHints(kLHintsCenterX, 10, 0, 5));

	pMainFrame->AddFrame(m_pLcioCollectionFrame);
}

//-------------------------------------------------------------------------------------------

LcioCollectionFrame::~LcioCollectionFrame() 
{

}


std::string LcioCollectionFrame::getSDHCALCollectionName() const
{
	const char *text = m_pSDHCALCollectionEntry->GetText();

	if(!text)
		return std::string("");
	else
	 return std::string(text);
}


} 

